@startuml

MyApp *-- TrainingListPage
MyApp *-- TrainingInputPage

TrainingListPage  -->  TrainingListViewModel
TrainingInputPage  -->  TrainingInputViewModel

TrainingListViewModel --> TrainingRepository
TrainingInputViewModel --> TrainingRepository
ChangeNotifier <|-- TrainingListViewModel

TrainingListViewModel --> TrainingItem
TrainingInputViewModel --> TrainingItem
TrainingRepository --> TrainingItem

class TrainingListViewModel {
  - trainingItemList : List<TrainingItem>
  + List<TrainingItem> getAllTrainingItem(string Name)
  + void updateTrainingItem(string Name, int count)
}

class TrainingInputViewModel {
  - trainingItem : TrainingItem
  + TrainingItem getTrainingItem(string Name)
  + void addTrainingItem(string Name, int count)
  + void updateTrainingItem(string Name, int count)
  + void deleteTrainingItem(string Name)
}

class TrainingRepository {
  + List<TrainingItem> getAllTrainingItem(string Name)
  + TrainingItem getTrainingItem(string Name)
  + void addTrainingItem(string Name, int count)
  + void updateTrainingItem(string Name, int count)
  + void deleteTrainingItem(string Name)
}

note left of TrainingRepository
  ストア(FireStore)にアクセスして
  データ操作を行う
end note

note right of TrainingRepository::getAllTrainingItem
  TrainingItem.fromJsonのようにモデル化して返す
end note

note right of TrainingRepository::getTrainingItem
  TrainingItem.fromJsonのようにモデル化して返す
end note

note right of TrainingRepository::addTrainingItem
  同じ名前は登録不可
end note

class TrainingItem {
  - Name : string
  - Count : int
  + String getName()
  + int getCount()
  + void changeName(String name)
  + void changeCount(int count)
}

@enduml