@startuml
entity 腕立て伏せ {
   id
  --
   name (名前)
   count (回数)
}

entity 腹筋 {
   id
  --
   name (名前)
   count (回数)
}

entity スクワット {
   id
  --
   name (名前)
   count (回数)
}

Menu ||..o| 腕立て伏せ
Menu ||..o| 腹筋
Menu ||..o| スクワット

@enduml