@startuml
entity 腕立て伏せ {
   id
  --
   name (名前)
   count (回数)
   unit (単位)
}

entity 腹筋 {
   id
  --
   name (名前)
   count (回数)
   unit (単位)
}

entity 瞑想 {
   id
  --
   name (名前)
   count (回数)
   unit (単位)
}

Menu ||..o| 腕立て伏せ
Menu ||..o| 腹筋
Menu ||..o| 瞑想

@enduml